site_name: MCCN Engine
theme:
    icon:
      repo: fontawesome/brands/github
    name: 'material'
    palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'blue'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'
    features:
      - content.code.copy
      - content.code.select
      - search.suggest
      - search.highlight
      - search.share
      - content.tabs.link

repo_url: https://github.com/aus-plant-phenomics-network/mccn-engine

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - Reference: api_reference.md

plugins:
  - search
  - table-reader
  - autorefs
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          paths: [stac_generator]
          options:
            docstring_style: google
            show_source: false
            heading_level: 2
            members_order: source
            annotations_path: source

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
